name: black-action
on: [pull_request]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Python files
        id: files
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.py')
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Run Black only on changed files
        if: steps.files.outputs.files != ''
        uses: rickstaa/action-black@v1
        with:
          black_args: "${{ steps.files.outputs.files }} --check"

      - name: Skip if no Python files changed
        if: steps.files.outputs.files == ''
        run: echo "No Python files changed in this PR."
